name: Github Action Study
run-name: ${{ github.actor }} is push somethine to study demo
on: [push]
jobs:
  Print-Log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{github.event_name}}"
      - run: echo "The job is now runnint on a ${{runner.os}}"
      - run: echo "The name of your branch is ${{github.ref}} and your respository is ${{github.repository}}"

      - name: Check Out Response Code
        uses: actions/checkout@v3
      - run: echo "The ${{github.repository}} has been cloned to the runner"
      - run: echo "The workflow is now ready to test your code on the runner"

      - name: List files in the repository
        run: |
          ls ${{github.workspace}}

      - run: echo "The job status is ${{job.status}}"

  Build-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.14.2
          cache: npm
          cache-dependency-path: ./
      - run: npm ci
      - run: npm run package
